### ISSUE TITLE
Replace turf inside with LatLngBounds contains

### ISSUE THREAD

**Issue by bmcbride** [chriswhong/crossfilter-geo-input#1]
Hey Chris,

This is awesome! I've done something similar to determine which points are within the current viewport in my BootLeaf template simply using Leaflet's built in LatLngBounds [`contains()`](http://leafletjs.com/reference.html#latlngbounds-contains) method. You may be able to save ~500kb by going that route and removing the turf dependency. Just a though and thanks again for sharing this with the community!

```
geoJsonLayer.eachLayer(function (layer) {
  if (map.getBounds().contains(layer.getLatLng())) {
    console.log(layer);
  }
});
```

**Comment by chriswhong** [comment]
Wow, I had no idea that contains() existed!  Thanks for the tip.

However I think I want to have the flexibility to filter by custom geometry
(allowing the user to draw a shape), and contains() looks like it only
works with a latlngbounds rectangle.


-Chris

**Comment by bmcbride** [comment]
Good deal! Looking forward to seeing how this progresses!
